headers = headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) '
                         'Chrome/112.0.0.0 Safari/537.36', 'Referrer': 'https://www.google.com/', 
                         'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8'}

base_url = "https://www.numbeo.com/cost-of-living/in/"

eu_cities = [{"city":"Amsterdam", "currency":"EUR"},
      {"city":"Athens", "currency":"EUR"},
      {"city":"Belgrade", "currency":"RSD"},
      {"city":"Berlin", "currency":"EUR"},
      {"city":"Bern", "currency":"CHF"},
      {"city":"Bratislava", "currency":"EUR"},
      {"city":"Brussels", "currency":"EUR"},
      {"city":"Bucharest", "currency":"RON"},
      {"city":"Budapest", "currency":"HUF"},
      {"city":"Copenhagen", "currency":"DKK"},
      {"city":"Dublin", "currency":"EUR"},
      {"city":"Helsinki", "currency":"EUR"},
      {"city":"Kiev", "currency":"UAH"},
      {"city":"Lisbon", "currency":"EUR"},
      {"city":"Ljubljana", "currency":"EUR"},
      {"city":"London", "currency":"GBP"},
      {"city":"Luxembourg", "currency":"EUR"},
      {"city":"Madrid", "currency":"EUR"},
      {"city":"Minsk", "currency":"BYN"},
      {"city":"Moscow", "currency":"RUB"},
      {"city":"Oslo", "currency":"NOK"},
      {"city":"Paris", "currency":"EUR"},
      {"city":"Podgorica", "currency":"EUR"},
      {"city":"Prague", "currency":"CZK"},
      {"city":"Reykjavik", "currency":"ISK"},
      {"city":"Riga", "currency":"EUR"},
      {"city":"Rome", "currency":"EUR"},
      {"city":"Sarajevo", "currency":"BAM"},
      {"city":"Skopje", "currency":"MKD"},
      {"city":"Sofia", "currency":"BGN"},
      {"city":"Stockholm", "currency":"SEK"},
      {"city":"Tallinn", "currency":"EUR"},
      {"city":"Tirana", "currency":"ALL"},
      {"city":"Valletta", "currency":"EUR"},
      {"city":"Vienna", "currency":"EUR"},
      {"city":"Vilnius", "currency":"EUR"},
      {"city":"Warsaw", "currency":"PLN"},
      {"city":"Zagreb", "currency":"EUR"},]

us_cities = [{"city":"New-York", "currency":"USD"},
             {"city":"Los-Angeles", "currency":"USD"},
             {"city":"Chicago", "currency":"USD"},
             {"city":"Houston", "currency":"USD"},
             {"city":"Philadelphia", "currency":"USD"},
             {"city":"Phoenix", "currency":"USD"},
             {"city":"San-Antonio", "currency":"USD"},
             {"city":"San-Diego", "currency":"USD"},
             {"city":"Dallas", "currency":"USD"},
             {"city":"San-Jose", "currency":"USD"},
             {"city":"Austin", "currency":"USD"},
             {"city":"Jacksonville", "currency":"USD"},
             {"city":"San-Francisco", "currency":"USD"},
             {"city":"Indianapolis", "currency":"USD"},
             {"city":"Columbus", "currency":"USD"},
             {"city":"Fort-Worth", "currency":"USD"},
             {"city":"Charlotte", "currency":"USD"},
             {"city":"Seattle", "currency":"USD"},
             {"city":"Denver", "currency":"USD"},
             {"city":"Washington", "currency":"USD"},]

base_column_names = ["date", "city", "currency"]

scrape_column_names = ["family_of_four", 
                "single_person_costs",
                "meal_inexp_restaurant",
                "meal_couple_midrange_restaurant",
                "mcmeal_mcdonalds",
                "dom_beer_restaurant",
                "imp_beer_restaurant",
                "cappuccino_restaurant",
                "cola_restaurant",
                "water_restaurant",
                "milk",
                "bread",
                "rice",
                "eggs",
                "local_cheese",
                "chicken_fillets",
                "beef",
                "apples",
                "banana",
                "oranges",
                "tomato",
                "potato",
                "onion",
                "lettuce",
                "water",
                "wine",
                "dom_beer",
                "imp_beer",
                "cigarettes",
                "pub_transp_one_way",
                "pub_transp_monthly",
                "taxi_start",
                "taxi_1km",
                "taxi_1hour",
                "gasoline",
                "vw_golf_or_equ",
                "toyota_corolla_or_equ",
                "utilities",
                "prepaid_mobile_tariff",
                "internet",
                "fitness_club_fee",
                "tennis_court_rent",
                "cinema",
                "private_preschool",
                "international_primary_school",
                "pair_of_jeans",
                "summer_dress",
                "pair_of_nike_shoes",
                "pair_of_leather_shoes",
                "apartment_1bedr_city_center",
                "apartment_1bedr_out_city_center",
                "apartment_3bedr_city_center",
                "apartment_3bedr_out_city_center",
                "price_sq_meter_city_center",
                "price_sq_meter_out_city_center",
                "avg_monthly_net_salary",
                "mortgage_interest_rate",
                "data_entries",
                "unique_contributors"]